In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlp
import seaborn as sns
from google.colab import files
data=files.upload()

Saving Original.csv to Original.csv

In [ ]:
data

{'Original.csv': b'date,[PS01=SLC03] Electrical conductivity (EC) [\xc2\xb5S/cm],[PS02] Electrical conductivity (EC) [\xc2\xb5S/cm],[PS03] Electrical conductivity (EC) [\xc2\xb5S/cm],[PS04] Electrical conductivity (EC) [\xc2\xb5S/cm],[SLC01] Electrical conductivity (EC) [\xc2\xb5S/cm],[SLC02] Electrical conductivity (EC) [\xc2\xb5S/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],[PS04] Nitrite (NO2-N) [mg NO2-N/L],[SLC01] Nitrite (NO2-N) [mg NO2-N/L],[SLC02] Nitrite (NO2-N) [mg NO2-N/L],[PS01=SLC03] Nitrate (NO3-N) [mg NO3-N/L],[PS02] Nitrate (NO3-N) [mg NO3-N/L],[PS03] Nitrate (NO3-N) [mg NO3-N/L],[PS04] Nitrate (NO3-N) [mg NO3-N/L],[SLC01] Nitrate (NO3-N) [mg NO3-N/L],[SLC02] Nitrate (NO3-N) [mg NO3-N/L],[PS01=SLC03] Total Nitrogen (TN) [mg N/L],[PS02] Total Nitrogen (TN) [mg N/L],[PS03] Total Nitrogen (TN) [mg N/L],[PS04] Total Nitrogen (TN) [mg N/L],[SLC01] Total Nitrogen (TN) [mg N/L],[SLC02] Total Nitrogen (TN) [mg N/L],[PS01=SLC03] Dissolved oxygen (DO) [mg/L],[PS02] Dissolved oxygen (DO) [mg/L],[PS03] Dissolved oxygen (DO) [mg/L],[PS04] Dissolved oxygen (DO) [mg/L],[SLC01] Dissolved oxygen (DO) [mg/L],[SLC02] Dissolved oxygen (DO) [mg/L],[PS01=SLC03] pH [NA],[PS02] pH [NA],[PS03] pH [NA],[PS04] pH [NA],[SLC01] pH [NA],[SLC02] pH [NA],[PS01=SLC03] Water temperature (Tw) [\xc2\xbaC],[PS02] Water temperature (Tw) [\xc2\xbaC],[PS03] Water temperature (Tw) [\xc2\xbaC],[PS04] Water temperature (Tw) [\xc2\xbaC],[SLC01] Water temperature (Tw) [\xc2\xbaC],[SLC02] Water temperature (Tw) [\xc2\xbaC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]\n2014-01-31,301.2,240.6,239.8,240.9,234.5,239.1,0.21,0.016,0.016,0.02,0.02,0.045,0.87,0.92,0.72,0.72,0.18,0.27,2.37,1.83,1.44,1.51,1.07,1.18,3.6,5.94,6.72,6.48,5.65,5.48,7.49,7.63,7.93,7.69,7.5,7.58,26.8,26.6,27.2,27.4,25.5,26.9,5.7,11.0,8.3,8.8,12.0,9.0\n2014-02-28,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2014-03-31,204.6,142.8,182.9,154.5,146.4,191.0,0.0065,0.0012,,0.014,0.0029,0.0029,0.34,0.54,0.51,0.54,0.1,0.16,0.99,1.34,1.28,1.26,0.96,1.08,7.48,6.51,7.03,7.04,7.18,7.88,7.83,7.7,7.57,7.61,7.65,7.63,19.7,22.4,21.9,22.1,18.7,18.8,13.0,15.0,19.0,15.0,18.0,15.0\n2014-04-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2014-05-31,187.3,132.3,104.6,95.5,143.7,173.6,0.016,0.016,0.016,0.016,0.016,0.016,0.6,0.61,0.6,0.52,0.88,0.55,1.02,1.28,1.29,1.25,1.42,1.29,8.06,7.14,7.1,6.71,,8.35,7.34,7.22,7.35,7.3,7.41,7.49,17.4,17.9,18.0,18.0,17.2,17.0,15.0,25.0,25.0,26.0,18.0,18.0\n2014-06-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2014-07-31,81.0,72.3,62.0,65.6,78.9,78.3,0.02,0.02,0.02,0.02,0.02,0.02,0.69,0.51,0.55,0.45,0.26,0.5,1.76,1.39,1.58,1.41,0.99,1.5,10.32,8.26,8.69,8.54,11.4,10.35,8.01,7.15,7.44,6.98,7.51,7.32,10.7,12.8,12.5,12.5,9.4,10.6,45.0,40.0,50.0,40.0,40.0,45.0\n2014-08-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2014-09-30,155.5,66.8,57.8,61.2,139.1,143.1,0.092,0.016,0.016,0.016,0.016,0.016,0.37,0.17,0.2,0.17,0.14,0.31,1.37,1.17,1.07,0.99,1.01,1.04,8.39,7.36,7.34,7.51,9.48,8.62,7.98,7.16,7.53,7.13,7.47,7.77,17.6,18.1,16.9,18.6,17.2,16.6,21.0,27.0,29.0,27.0,20.0,22.0\n2014-10-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2014-11-30,,105.9,108.0,102.3,169.5,162.2,,0.016,0.016,0.016,0.016,0.016,,0.02,0.02,0.02,0.02,0.02,,1.4,1.44,1.29,1.13,1.23,,7.64,7.04,7.28,7.51,8.12,,7.6,7.41,7.55,7.75,7.75,,24.0,24.2,23.0,22.0,21.9,,13.0,19.0,15.0,16.0,18.0\n2014-12-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2015-01-31,,143.7,201.3,158.8,265.3,237.9,,0.016,0.016,0.016,0.016,0.016,,0.37,0.7,0.7,0.26,0.63,,1.05,1.01,1.04,0.43,0.93,,6.22,6.1,6.37,7.17,6.71,,7.95,7.82,7.72,7.95,7.94,,25.4,26.0,25.9,22.4,22.3,,14.0,16.0,13.0,33.0,29.0\n2015-02-28,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2015-03-31,,201.8,212.4,205.6,375.1,324.1,,0.016,0.016,0.016,0.016,0.016,,0.44,0.43,0.26,0.06,0.02,,0.94,0.94,0.89,0.77,0.49,,6.82,6.25,6.59,6.58,6.68,,8.02,8.11,7.88,7.97,8.19,,26.4,24.2,26.3,23.1,25.4,,12.0,14.0,15.0,7.4,1.8\n2015-04-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2015-05-31,,203.1,257.9,224.8,371.4,443.5,,0.016,0.016,0.016,0.016,0.016,,0.68,0.72,0.71,0.053,0.062,,1.25,1.24,1.25,0.46,0.8,,9.05,8.39,8.95,8.64,8.46,,8.05,7.96,7.99,7.89,8.18,,18.7,18.1,18.2,17.2,18.9,,25.0,28.0,29.0,30.0,5.1\n2015-06-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2015-07-31,,222.4,327.9,239.7,327.1,389.0,,0.0,0.0,0.0,0.0,0.0,,0.56,0.3,0.63,0.074,0.1,,1.11,0.99,1.14,1.1,0.6,,7.93,9.05,7.95,8.55,8.85,,8.0,8.61,8.15,8.06,8.78,,11.6,11.1,11.2,8.4,9.8,,27.0,12.0,26.0,60.0,2.2\n2015-08-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2015-09-30,,144.3,191.5,164.6,286.5,274.8,,0.016,0.016,0.016,0.016,0.016,,0.76,0.63,0.66,0.11,0.31,,1.69,1.63,1.67,0.73,1.06,,8.52,8.73,9.07,8.83,8.81,,8.2,8.42,8.19,8.55,8.36,,14.9,15.3,15.4,14.8,15.2,,24.0,25.0,24.0,16.0,14.0\n2015-10-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2015-11-30,344.8,184.7,192.6,188.3,315.0,336.2,0.023,0.023,0.023,0.023,0.023,0.023,0.36,0.49,0.46,0.44,0.1,0.17,1.06,1.16,1.13,1.13,0.71,0.96,7.45,8.0,8.24,8.1,7.69,7.76,7.87,7.84,7.8,7.84,7.69,7.83,22.0,21.9,21.4,21.7,21.6,21.8,5.5,22.0,23.0,22.0,9.2,9.5\n2015-12-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-01-31,266.9,165.4,166.6,176.2,168.2,243.2,0.019,0.019,0.019,0.019,0.019,0.019,0.55,0.78,0.49,0.42,0.076,0.079,1.43,1.27,1.18,1.22,0.86,0.75,6.48,7.42,7.45,7.99,7.39,6.97,8.1,7.4,7.49,7.88,7.98,7.99,25.8,26.9,26.3,26.3,24.2,26.2,9.4,13.0,14.0,17.0,12.0,12.0\n2016-02-29,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-03-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-04-30,,139.6,156.8,142.2,230.5,339.1,,0.023,0.023,0.023,0.023,0.023,,0.55,0.6,0.56,0.16,0.18,,1.11,1.16,1.14,0.93,0.91,,7.88,7.91,8.02,7.84,7.73,,7.79,7.8,7.78,7.62,7.8,,21.0,21.0,21.0,19.8,20.1,,20.0,28.0,21.0,45.0,5.0\n2016-05-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-06-30,,133.4,174.2,130.7,239.9,267.9,,0.023,0.023,0.023,0.023,0.023,,0.55,0.53,0.53,0.12,0.31,,1.41,1.35,1.38,0.64,0.95,,9.95,9.93,9.48,9.86,10.4,,7.52,7.77,7.35,7.71,7.75,,12.7,11.4,11.8,12.1,11.6,,16.0,13.0,16.0,7.0,8.2\n2016-07-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-08-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-09-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-10-31,328.6,149.2,205.4,153.4,272.6,303.5,0.019,0.019,0.019,0.019,0.019,0.019,0.017,0.39,0.43,0.16,0.017,0.017,1.52,1.53,1.53,1.5,0.83,0.83,8.68,9.1,8.62,8.78,8.34,8.44,8.36,8.11,8.41,8.0,8.03,8.19,19.5,23.3,19.1,20.6,18.9,18.0,3.3,20.0,17.0,19.0,9.2,4.7\n2016-11-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2016-12-31,289.5,255.4,268.8,255.2,196.3,270.4,0.0414,0.0414,,,0.0414,0.0414,0.83,0.4,,,0.39,0.43,2.14,1.03,,,1.61,1.62,6.78,7.75,7.82,7.74,6.55,7.32,7.05,7.34,7.81,7.28,7.61,7.78,23.8,24.4,25.6,26.3,22.4,22.9,14.0,8.7,,,21.0,12.0\n2017-01-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2017-02-28,245.7,256.4,195.1,221.7,311.1,215.4,0.0,0.0,0.0,0.0,0.0,0.0,0.58,0.15,0.39,0.26,0.64,0.31,1.44,0.81,1.11,0.93,1.52,1.28,5.4,9.2,5.51,7.5,5.3,6.16,7.82,8.1,7.72,7.56,7.85,8.01,29.2,27.3,27.4,27.8,24.0,25.7,13.0,4.4,12.0,9.1,16.0,13.0\n2017-03-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2017-04-30,331.3,177.7,208.6,178.2,329.9,261.7,0.049,0.0,0.0,0.0,0.0,0.0,0.95,0.71,0.73,0.7,0.12,0.06,1.51,1.17,1.29,1.22,0.72,0.74,7.21,7.5,8.1,9.14,8.24,8.07,8.02,7.7,7.67,7.65,7.71,7.88,18.2,19.7,19.1,19.6,18.4,18.5,2.9,16.0,21.0,16.0,2.7,3.4\n2017-05-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2017-06-30,229.1,145.0,130.0,138.2,188.8,205.6,0.0,0.0,0.0,0.0,0.0,0.0,0.73,0.64,0.42,0.52,0.16,0.3,1.51,1.55,1.52,1.5,0.72,1.08,10.28,9.37,9.53,9.47,10.37,10.3,8.0,7.62,7.88,7.52,7.8,7.93,10.4,,12.1,12.4,9.4,8.9,14.0,23.0,28.0,26.0,16.0,14.0\n2017-07-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2017-08-31,116.0,,,,52.8,113.8,0.0009,,,,0.0,0.0,0.25,,,,0.17,0.2,2.01,,,,1.62,1.59,9.26,,,,9.09,9.29,7.75,,,,7.74,7.53,13.9,,,,13.0,13.7,57.0,,,,49.0,41.0\n2017-09-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2017-10-31,288.9,115.6,187.1,157.7,261.8,274.6,0.054,0.0,0.0,0.0,0.0,0.0,0.75,0.64,0.59,0.68,0.18,0.35,1.67,1.32,1.48,1.32,0.82,0.98,6.68,8.15,7.7,8.15,7.25,8.05,7.31,7.27,7.38,7.39,7.4,7.48,19.3,18.9,18.9,18.8,18.6,18.2,8.8,26.0,22.0,24.0,15.0,12.0\n2017-11-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2017-12-31,410.5,227.1,238.8,229.9,332.5,380.6,0.15,0.0009,0.0009,0.0,0.049,0.0009,0.38,0.63,0.55,0.59,0.047,0.0,1.31,1.28,1.49,1.41,1.46,0.8,11.3,8.28,8.07,8.44,7.17,7.95,7.93,7.77,7.63,7.76,7.28,7.57,26.5,25.3,25.2,25.1,23.9,25.2,1.5,11.0,13.0,13.0,5.0,2.0\n2018-01-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2018-02-28,238.9,271.4,276.9,275.9,315.6,443.6,0.055,0.0,0.02,0.006,0.0,0.007,0.89,0.19,0.08,0.11,0.13,0.17,2.2,0.82,0.89,0.72,0.88,1.14,5.33,6.94,7.59,8.32,7.73,7.21,7.42,7.85,7.94,8.13,7.83,7.93,24.6,24.7,25.5,25.5,23.8,25.9,73.5,4.81,10.2,5.86,10.2,12.8\n2018-03-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2018-04-30,,217.2,216.0,215.5,390.6,459.0,,0.0005,0.0005,0.0005,0.0,0.006,,0.48,0.57,0.47,0.1,0.054,,0.98,1.1,1.02,0.51,0.92,,7.61,7.1,7.63,6.6,6.28,,7.83,7.73,7.84,7.76,7.7,,22.1,21.7,22.0,22.7,23.4,,10.0,14.0,19.0,13.0,18.0\n2018-05-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2018-06-30,277.7,191.7,225.9,198.4,184.2,256.3,0.0005,0.006,0.015,0.008,0.0,0.0005,1.1,0.71,0.81,0.74,0.34,0.6,2.14,1.41,1.75,1.52,1.4,1.31,9.64,10.25,9.97,10.13,9.68,11.12,7.94,7.93,7.93,7.9,8.03,7.93,12.0,13.0,12.4,12.7,10.9,11.0,16.5,16.1,17.8,17.3,29.1,15.8\n2018-07-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2018-08-31,226.7,98.4,124.7,106.9,166.4,207.6,0.014,0.016,0.015,0.014,0.006,0.007,0.5,0.34,0.45,0.39,0.13,0.31,1.62,1.57,1.57,1.49,0.91,1.16,10.32,9.75,10.13,9.88,10.07,10.72,7.66,6.82,7.13,7.24,7.82,7.66,13.4,12.6,13.1,13.3,13.1,12.7,21.5,40.6,37.7,41.4,22.7,21.3\n2018-09-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2018-10-31,258.0,150.9,143.2,139.8,198.9,233.6,0.012,0.013,0.023,0.019,0.0,0.0,0.38,0.39,0.35,0.32,0.14,0.25,1.53,1.62,1.51,1.58,1.21,1.9,8.06,6.09,7.8,6.8,8.02,8.47,7.14,6.81,6.81,6.64,7.25,7.14,21.1,20.1,22.6,20.9,20.7,19.3,20.4,24.9,23.7,28.4,20.1,16.4\n2018-11-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2018-12-31,309.7,203.5,223.4,213.8,258.4,275.3,0.017,0.0005,0.012,0.0005,0.0005,0.0005,0.57,0.63,0.65,0.62,0.12,0.19,1.25,1.09,1.19,1.14,1.02,0.96,6.31,7.51,7.41,7.63,6.98,7.18,7.5,7.51,7.06,7.5,7.5,7.43,24.5,21.6,22.5,22.8,22.7,22.5,8.31,17.3,18.0,17.6,15.0,15.0\n2019-01-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2019-02-28,253.1,,,,224.0,219.3,0.0005,,,,0.0005,0.0005,0.46,,,,0.25,0.4,1.32,,,,1.26,1.39,6.57,,,,7.64,6.47,7.11,,,,7.25,7.45,30.0,,,,26.7,27.0,13.2,,,,14.3,14.5\n2019-03-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2019-04-30,388.8,183.1,202.9,185.5,329.1,358.8,0.017,0.0,0.008,0.0,0.0,0.0005,0.7,0.5,0.51,0.52,0.21,0.007,,,,,,,8.96,7.27,7.56,7.68,8.96,9.28,7.93,7.73,7.67,7.6,6.55,7.69,16.2,19.4,19.2,19.3,16.2,16.8,13.6,25.3,26.9,20.6,13.1,13.5\n2019-05-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2019-06-30,287.9,,,,260.5,262.7,0.021,,,,0.0005,0.0,0.62,,,,0.54,0.3,1.92,,,,1.33,1.38,8.76,,,,8.96,9.16,7.35,,,,7.29,7.36,16.3,,,,14.1,15.1,15.8,,,,11.9,16.4\n2019-07-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2019-08-31,94.8,,,,93.5,90.7,0.005,,,,0.0,0.005,0.32,,,,0.11,0.28,1.65,,,,1.16,1.62,10.51,,,,10.57,10.65,7.41,,,,7.9,7.51,10.5,,,,10.5,10.3,48.5,,,,38.8,43.9\n2019-09-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2019-10-31,193.9,98.2,67.1,74.3,146.9,167.2,0.009,0.008,0.008,0.008,0.0009,0.0009,0.42,0.25,0.17,0.17,0.16,0.38,1.68,1.51,1.41,1.45,1.53,1.53,8.58,6.91,7.37,7.27,8.74,8.49,,,,,,,18.5,17.5,16.7,17.5,16.7,17.1,26.2,26.1,25.2,25.2,26.4,28.1\n2019-11-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2019-12-31,437.5,167.5,173.4,174.5,355.6,412.0,0.094,0.005,0.005,0.0,0.0009,0.0009,0.36,0.6,0.54,0.54,0.1,0.0126,2.28,1.85,1.84,1.77,1.18,1.28,14.84,8.26,8.29,8.21,7.46,7.96,7.5,6.57,6.71,6.56,7.3,7.24,27.8,25.7,25.7,25.6,25.1,28.2,,,,,,\n2020-01-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2020-02-29,382.8,216.6,225.6,219.4,356.2,406.1,0.017,0.0,0.0,0.0,0.0076,0.0,0.91,0.52,0.55,0.55,0.18,0.0,1.55,1.0,1.11,1.07,0.78,0.78,7.18,7.27,7.25,7.37,6.14,8.04,7.93,7.99,7.99,8.05,7.82,8.09,26.9,26.7,26.2,26.3,24.6,26.7,10.4,17.1,18.3,23.2,18.1,6.14\n2020-03-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2020-04-30,416.1,,,,223.5,423.4,0.077,,,,0.0,0.0009,0.87,,,,0.11,0.06,1.66,,,,1.82,1.03,7.99,,,,7.34,8.51,7.86,,,,7.81,8.35,19.1,,,,18.9,19.3,16.1,,,,64.7,8.96\n2020-05-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2020-06-30,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2020-07-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2020-08-31,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n'}

In [ ]:
df=pd.read_csv('Original.csv')
df

,date,[PS01=SLC03] Electrical conductivity (EC) [µS/cm],[PS02] Electrical conductivity (EC) [µS/cm],[PS03] Electrical conductivity (EC) [µS/cm],[PS04] Electrical conductivity (EC) [µS/cm],[SLC01] Electrical conductivity (EC) [µS/cm],[SLC02] Electrical conductivity (EC) [µS/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],...,[PS03] Water temperature (Tw) [ºC],[PS04] Water temperature (Tw) [ºC],[SLC01] Water temperature (Tw) [ºC],[SLC02] Water temperature (Tw) [ºC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]
0,2014-01-31,301.2,240.6,239.8,240.9,234.5,239.1,0.2100,0.0160,0.016,...,27.2,27.4,25.5,26.9,5.7,11.0,8.3,8.8,12.0,9.00
1,2014-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-03-31,204.6,142.8,182.9,154.5,146.4,191.0,0.0065,0.0012,NaN,...,21.9,22.1,18.7,18.8,13.0,15.0,19.0,15.0,18.0,15.00
3,2014-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-05-31,187.3,132.3,104.6,95.5,143.7,173.6,0.0160,0.0160,0.016,...,18.0,18.0,17.2,17.0,15.0,25.0,25.0,26.0,18.0,18.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2020-04-30,416.1,NaN,NaN,NaN,223.5,423.4,0.0770,NaN,NaN,...,NaN,NaN,18.9,19.3,16.1,NaN,NaN,NaN,64.7,8.96
76,2020-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,2020-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2020-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(80, 49)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 49 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   date                                               80 non-null     object
 1   [PS01=SLC03] Electrical conductivity (EC) [µS/cm]  28 non-null     float64
 2   [PS02] Electrical conductivity (EC) [µS/cm]        32 non-null     float64
 3   [PS03] Electrical conductivity (EC) [µS/cm]        32 non-null     float64
 4   [PS04] Electrical conductivity (EC) [µS/cm]        32 non-null     float64
 5   [SLC01] Electrical conductivity (EC) [µS/cm]       37 non-null     float64
 6   [SLC02] Electrical conductivity (EC) [µS/cm]       37 non-null     float64
 7   [PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L]          28 non-null     float64
 8   [PS02] Nitrite (NO2-N) [mg NO2-N/L]                32 non-null     float64
 9   [PS03] Nitrite (NO2-N) [mg NO2-N/L]                30 non-null     float64
 10  [PS04] Nitrite (NO2-N) [mg NO2-N/L]                31 non-null     float64
 11  [SLC01] Nitrite (NO2-N) [mg NO2-N/L]               37 non-null     float64
 12  [SLC02] Nitrite (NO2-N) [mg NO2-N/L]               37 non-null     float64
 13  [PS01=SLC03] Nitrate (NO3-N) [mg NO3-N/L]          28 non-null     float64
 14  [PS02] Nitrate (NO3-N) [mg NO3-N/L]                32 non-null     float64
 15  [PS03] Nitrate (NO3-N) [mg NO3-N/L]                31 non-null     float64
 16  [PS04] Nitrate (NO3-N) [mg NO3-N/L]                31 non-null     float64
 17  [SLC01] Nitrate (NO3-N) [mg NO3-N/L]               37 non-null     float64
 18  [SLC02] Nitrate (NO3-N) [mg NO3-N/L]               37 non-null     float64
 19  [PS01=SLC03] Total Nitrogen (TN) [mg N/L]          27 non-null     float64
 20  [PS02] Total Nitrogen (TN) [mg N/L]                31 non-null     float64
 21  [PS03] Total Nitrogen (TN) [mg N/L]                30 non-null     float64
 22  [PS04] Total Nitrogen (TN) [mg N/L]                30 non-null     float64
 23  [SLC01] Total Nitrogen (TN) [mg N/L]               36 non-null     float64
 24  [SLC02] Total Nitrogen (TN) [mg N/L]               36 non-null     float64
 25  [PS01=SLC03] Dissolved oxygen (DO) [mg/L]          28 non-null     float64
 26  [PS02] Dissolved oxygen (DO) [mg/L]                32 non-null     float64
 27  [PS03] Dissolved oxygen (DO) [mg/L]                32 non-null     float64
 28  [PS04] Dissolved oxygen (DO) [mg/L]                32 non-null     float64
 29  [SLC01] Dissolved oxygen (DO) [mg/L]               36 non-null     float64
 30  [SLC02] Dissolved oxygen (DO) [mg/L]               37 non-null     float64
 31  [PS01=SLC03] pH [NA]                               27 non-null     float64
 32  [PS02] pH [NA]                                     31 non-null     float64
 33  [PS03] pH [NA]                                     31 non-null     float64
 34  [PS04] pH [NA]                                     31 non-null     float64
 35  [SLC01] pH [NA]                                    36 non-null     float64
 36  [SLC02] pH [NA]                                    36 non-null     float64
 37  [PS01=SLC03] Water temperature (Tw) [ºC]           28 non-null     float64
 38  [PS02] Water temperature (Tw) [ºC]                 31 non-null     float64
 39  [PS03] Water temperature (Tw) [ºC]                 32 non-null     float64
 40  [PS04] Water temperature (Tw) [ºC]                 32 non-null     float64
 41  [SLC01] Water temperature (Tw) [ºC]                37 non-null     float64
 42  [SLC02] Water temperature (Tw) [ºC]                37 non-null     float64
 43  [PS01=SLC03] Turbidity (Turb) [NTU]                27 non-null     float64
 44  [PS02] Turbidity (Turb) [NTU]                      31 non-null     float64
 45  [PS03] Turbidity (Turb) [NTU]                      30 non-null     float64
 46  [PS04] Turbidity (Turb) [NTU]                      30 non-null     float64
 47  [SLC01] Turbidity (Turb) [NTU]                     36 non-null     float64
 48  [SLC02] Turbidity (Turb) [NTU]                     36 non-null     float64
dtypes: float64(48), object(1)
memory usage: 30.8+ KB

In [ ]:
df.head()

,date,[PS01=SLC03] Electrical conductivity (EC) [µS/cm],[PS02] Electrical conductivity (EC) [µS/cm],[PS03] Electrical conductivity (EC) [µS/cm],[PS04] Electrical conductivity (EC) [µS/cm],[SLC01] Electrical conductivity (EC) [µS/cm],[SLC02] Electrical conductivity (EC) [µS/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],...,[PS03] Water temperature (Tw) [ºC],[PS04] Water temperature (Tw) [ºC],[SLC01] Water temperature (Tw) [ºC],[SLC02] Water temperature (Tw) [ºC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]
0,2014-01-31,301.2,240.6,239.8,240.9,234.5,239.1,0.2100,0.0160,0.016,...,27.2,27.4,25.5,26.9,5.7,11.0,8.3,8.8,12.0,9.0
1,2014-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-03-31,204.6,142.8,182.9,154.5,146.4,191.0,0.0065,0.0012,NaN,...,21.9,22.1,18.7,18.8,13.0,15.0,19.0,15.0,18.0,15.0
3,2014-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-05-31,187.3,132.3,104.6,95.5,143.7,173.6,0.0160,0.0160,0.016,...,18.0,18.0,17.2,17.0,15.0,25.0,25.0,26.0,18.0,18.0

In [ ]:
df.tail()

,date,[PS01=SLC03] Electrical conductivity (EC) [µS/cm],[PS02] Electrical conductivity (EC) [µS/cm],[PS03] Electrical conductivity (EC) [µS/cm],[PS04] Electrical conductivity (EC) [µS/cm],[SLC01] Electrical conductivity (EC) [µS/cm],[SLC02] Electrical conductivity (EC) [µS/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],...,[PS03] Water temperature (Tw) [ºC],[PS04] Water temperature (Tw) [ºC],[SLC01] Water temperature (Tw) [ºC],[SLC02] Water temperature (Tw) [ºC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]
75,2020-04-30,416.1,NaN,NaN,NaN,223.5,423.4,0.077,NaN,NaN,...,NaN,NaN,18.9,19.3,16.1,NaN,NaN,NaN,64.7,8.96
76,2020-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,2020-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2020-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.describe()

,[PS01=SLC03] Electrical conductivity (EC) [µS/cm],[PS02] Electrical conductivity (EC) [µS/cm],[PS03] Electrical conductivity (EC) [µS/cm],[PS04] Electrical conductivity (EC) [µS/cm],[SLC01] Electrical conductivity (EC) [µS/cm],[SLC02] Electrical conductivity (EC) [µS/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],[PS04] Nitrite (NO2-N) [mg NO2-N/L],...,[PS03] Water temperature (Tw) [ºC],[PS04] Water temperature (Tw) [ºC],[SLC01] Water temperature (Tw) [ºC],[SLC02] Water temperature (Tw) [ºC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]
count,28.000000,32.000000,32.000000,32.000000,37.000000,37.000000,28.000000,32.000000,30.000000,31.000000,...,32.000000,32.000000,37.000000,37.000000,27.000000,31.000000,30.000000,30.000000,36.000000,36.000000
mean,269.528571,169.500000,185.912500,171.537500,241.629730,272.545946,0.037136,0.010859,0.012080,0.010613,...,20.265625,20.496875,18.618919,19.175676,19.004074,19.203548,20.936667,20.682000,21.525000,15.186111
std,93.911053,53.684076,62.925198,56.174795,88.739885,101.455279,0.049056,0.010239,0.008421,0.008807,...,5.168865,5.126684,5.186834,5.621210,17.326920,8.673142,8.745382,8.095222,14.894455,10.838258
min,81.000000,66.800000,57.800000,61.200000,52.800000,78.300000,0.000000,0.000000,0.000000,0.000000,...,11.100000,11.200000,8.400000,8.900000,1.500000,4.400000,8.300000,5.860000,2.700000,1.800000
25%,221.175000,138.050000,153.400000,139.400000,169.500000,207.600000,0.008375,0.000375,0.001925,0.000000,...,16.850000,17.875000,14.800000,15.200000,9.100000,13.000000,14.000000,15.250000,12.000000,8.770000
50%,272.300000,166.450000,193.850000,175.350000,239.900000,262.700000,0.018000,0.014500,0.016000,0.014000,...,21.200000,20.950000,18.900000,18.900000,14.000000,17.300000,19.000000,19.800000,16.000000,13.750000
75%,329.275000,206.775000,223.950000,216.475000,315.600000,339.100000,0.050250,0.016000,0.018250,0.017500,...,25.275000,25.525000,22.700000,23.400000,20.700000,25.000000,25.150000,25.800000,27.075000,18.000000
max,437.500000,271.400000,327.900000,275.900000,390.600000,459.000000,0.210000,0.041400,0.023000,0.023000,...,27.400000,27.800000,26.700000,28.200000,73.500000,40.600000,50.000000,41.400000,64.700000,45.000000

In [ ]:
df.columns

Index(['date', '[PS01=SLC03] Electrical conductivity (EC) [µS/cm]',
       '[PS02] Electrical conductivity (EC) [µS/cm]',
       '[PS03] Electrical conductivity (EC) [µS/cm]',
       '[PS04] Electrical conductivity (EC) [µS/cm]',
       '[SLC01] Electrical conductivity (EC) [µS/cm]',
       '[SLC02] Electrical conductivity (EC) [µS/cm]',
       '[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L]',
       '[PS02] Nitrite (NO2-N) [mg NO2-N/L]',
       '[PS03] Nitrite (NO2-N) [mg NO2-N/L]',
       '[PS04] Nitrite (NO2-N) [mg NO2-N/L]',
       '[SLC01] Nitrite (NO2-N) [mg NO2-N/L]',
       '[SLC02] Nitrite (NO2-N) [mg NO2-N/L]',
       '[PS01=SLC03] Nitrate (NO3-N) [mg NO3-N/L]',
       '[PS02] Nitrate (NO3-N) [mg NO3-N/L]',
       '[PS03] Nitrate (NO3-N) [mg NO3-N/L]',
       '[PS04] Nitrate (NO3-N) [mg NO3-N/L]',
       '[SLC01] Nitrate (NO3-N) [mg NO3-N/L]',
       '[SLC02] Nitrate (NO3-N) [mg NO3-N/L]',
       '[PS01=SLC03] Total Nitrogen (TN) [mg N/L]',
       '[PS02] Total Nitrogen (TN) [mg N/L]',
       '[PS03] Total Nitrogen (TN) [mg N/L]',
       '[PS04] Total Nitrogen (TN) [mg N/L]',
       '[SLC01] Total Nitrogen (TN) [mg N/L]',
       '[SLC02] Total Nitrogen (TN) [mg N/L]',
       '[PS01=SLC03] Dissolved oxygen (DO) [mg/L]',
       '[PS02] Dissolved oxygen (DO) [mg/L]',
       '[PS03] Dissolved oxygen (DO) [mg/L]',
       '[PS04] Dissolved oxygen (DO) [mg/L]',
       '[SLC01] Dissolved oxygen (DO) [mg/L]',
       '[SLC02] Dissolved oxygen (DO) [mg/L]', '[PS01=SLC03] pH [NA]',
       '[PS02] pH [NA]', '[PS03] pH [NA]', '[PS04] pH [NA]', '[SLC01] pH [NA]',
       '[SLC02] pH [NA]', '[PS01=SLC03] Water temperature (Tw) [ºC]',
       '[PS02] Water temperature (Tw) [ºC]',
       '[PS03] Water temperature (Tw) [ºC]',
       '[PS04] Water temperature (Tw) [ºC]',
       '[SLC01] Water temperature (Tw) [ºC]',
       '[SLC02] Water temperature (Tw) [ºC]',
       '[PS01=SLC03] Turbidity (Turb) [NTU]', '[PS02] Turbidity (Turb) [NTU]',
       '[PS03] Turbidity (Turb) [NTU]', '[PS04] Turbidity (Turb) [NTU]',
       '[SLC01] Turbidity (Turb) [NTU]', '[SLC02] Turbidity (Turb) [NTU]'],
      dtype='object')

In [ ]:
df.isnull().sum()

date                                                  0
[PS01=SLC03] Electrical conductivity (EC) [µS/cm]    52
[PS02] Electrical conductivity (EC) [µS/cm]          48
[PS03] Electrical conductivity (EC) [µS/cm]          48
[PS04] Electrical conductivity (EC) [µS/cm]          48
[SLC01] Electrical conductivity (EC) [µS/cm]         43
[SLC02] Electrical conductivity (EC) [µS/cm]         43
[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L]            52
[PS02] Nitrite (NO2-N) [mg NO2-N/L]                  48
[PS03] Nitrite (NO2-N) [mg NO2-N/L]                  50
[PS04] Nitrite (NO2-N) [mg NO2-N/L]                  49
[SLC01] Nitrite (NO2-N) [mg NO2-N/L]                 43
[SLC02] Nitrite (NO2-N) [mg NO2-N/L]                 43
[PS01=SLC03] Nitrate (NO3-N) [mg NO3-N/L]            52
[PS02] Nitrate (NO3-N) [mg NO3-N/L]                  48
[PS03] Nitrate (NO3-N) [mg NO3-N/L]                  49
[PS04] Nitrate (NO3-N) [mg NO3-N/L]                  49
[SLC01] Nitrate (NO3-N) [mg NO3-N/L]                 43
[SLC02] Nitrate (NO3-N) [mg NO3-N/L]                 43
[PS01=SLC03] Total Nitrogen (TN) [mg N/L]            53
[PS02] Total Nitrogen (TN) [mg N/L]                  49
[PS03] Total Nitrogen (TN) [mg N/L]                  50
[PS04] Total Nitrogen (TN) [mg N/L]                  50
[SLC01] Total Nitrogen (TN) [mg N/L]                 44
[SLC02] Total Nitrogen (TN) [mg N/L]                 44
[PS01=SLC03] Dissolved oxygen (DO) [mg/L]            52
[PS02] Dissolved oxygen (DO) [mg/L]                  48
[PS03] Dissolved oxygen (DO) [mg/L]                  48
[PS04] Dissolved oxygen (DO) [mg/L]                  48
[SLC01] Dissolved oxygen (DO) [mg/L]                 44
[SLC02] Dissolved oxygen (DO) [mg/L]                 43
[PS01=SLC03] pH [NA]                                 53
[PS02] pH [NA]                                       49
[PS03] pH [NA]                                       49
[PS04] pH [NA]                                       49
[SLC01] pH [NA]                                      44
[SLC02] pH [NA]                                      44
[PS01=SLC03] Water temperature (Tw) [ºC]             52
[PS02] Water temperature (Tw) [ºC]                   49
[PS03] Water temperature (Tw) [ºC]                   48
[PS04] Water temperature (Tw) [ºC]                   48
[SLC01] Water temperature (Tw) [ºC]                  43
[SLC02] Water temperature (Tw) [ºC]                  43
[PS01=SLC03] Turbidity (Turb) [NTU]                  53
[PS02] Turbidity (Turb) [NTU]                        49
[PS03] Turbidity (Turb) [NTU]                        50
[PS04] Turbidity (Turb) [NTU]                        50
[SLC01] Turbidity (Turb) [NTU]                       44
[SLC02] Turbidity (Turb) [NTU]                       44
dtype: int64

In [ ]:
df.isnull().mean()

date                                                 0.0000
[PS01=SLC03] Electrical conductivity (EC) [µS/cm]    0.6500
[PS02] Electrical conductivity (EC) [µS/cm]          0.6000
[PS03] Electrical conductivity (EC) [µS/cm]          0.6000
[PS04] Electrical conductivity (EC) [µS/cm]          0.6000
[SLC01] Electrical conductivity (EC) [µS/cm]         0.5375
[SLC02] Electrical conductivity (EC) [µS/cm]         0.5375
[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L]            0.6500
[PS02] Nitrite (NO2-N) [mg NO2-N/L]                  0.6000
[PS03] Nitrite (NO2-N) [mg NO2-N/L]                  0.6250
[PS04] Nitrite (NO2-N) [mg NO2-N/L]                  0.6125
[SLC01] Nitrite (NO2-N) [mg NO2-N/L]                 0.5375
[SLC02] Nitrite (NO2-N) [mg NO2-N/L]                 0.5375
[PS01=SLC03] Nitrate (NO3-N) [mg NO3-N/L]            0.6500
[PS02] Nitrate (NO3-N) [mg NO3-N/L]                  0.6000
[PS03] Nitrate (NO3-N) [mg NO3-N/L]                  0.6125
[PS04] Nitrate (NO3-N) [mg NO3-N/L]                  0.6125
[SLC01] Nitrate (NO3-N) [mg NO3-N/L]                 0.5375
[SLC02] Nitrate (NO3-N) [mg NO3-N/L]                 0.5375
[PS01=SLC03] Total Nitrogen (TN) [mg N/L]            0.6625
[PS02] Total Nitrogen (TN) [mg N/L]                  0.6125
[PS03] Total Nitrogen (TN) [mg N/L]                  0.6250
[PS04] Total Nitrogen (TN) [mg N/L]                  0.6250
[SLC01] Total Nitrogen (TN) [mg N/L]                 0.5500
[SLC02] Total Nitrogen (TN) [mg N/L]                 0.5500
[PS01=SLC03] Dissolved oxygen (DO) [mg/L]            0.6500
[PS02] Dissolved oxygen (DO) [mg/L]                  0.6000
[PS03] Dissolved oxygen (DO) [mg/L]                  0.6000
[PS04] Dissolved oxygen (DO) [mg/L]                  0.6000
[SLC01] Dissolved oxygen (DO) [mg/L]                 0.5500
[SLC02] Dissolved oxygen (DO) [mg/L]                 0.5375
[PS01=SLC03] pH [NA]                                 0.6625
[PS02] pH [NA]                                       0.6125
[PS03] pH [NA]                                       0.6125
[PS04] pH [NA]                                       0.6125
[SLC01] pH [NA]                                      0.5500
[SLC02] pH [NA]                                      0.5500
[PS01=SLC03] Water temperature (Tw) [ºC]             0.6500
[PS02] Water temperature (Tw) [ºC]                   0.6125
[PS03] Water temperature (Tw) [ºC]                   0.6000
[PS04] Water temperature (Tw) [ºC]                   0.6000
[SLC01] Water temperature (Tw) [ºC]                  0.5375
[SLC02] Water temperature (Tw) [ºC]                  0.5375
[PS01=SLC03] Turbidity (Turb) [NTU]                  0.6625
[PS02] Turbidity (Turb) [NTU]                        0.6125
[PS03] Turbidity (Turb) [NTU]                        0.6250
[PS04] Turbidity (Turb) [NTU]                        0.6250
[SLC01] Turbidity (Turb) [NTU]                       0.5500
[SLC02] Turbidity (Turb) [NTU]                       0.5500
dtype: float64

In [ ]:
subset=df.fillna(df.mean().iloc[0])
subset

<ipython-input-29-e28de765b28c>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  subset=df.fillna(df.mean().iloc[0])

,date,[PS01=SLC03] Electrical conductivity (EC) [µS/cm],[PS02] Electrical conductivity (EC) [µS/cm],[PS03] Electrical conductivity (EC) [µS/cm],[PS04] Electrical conductivity (EC) [µS/cm],[SLC01] Electrical conductivity (EC) [µS/cm],[SLC02] Electrical conductivity (EC) [µS/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],...,[PS03] Water temperature (Tw) [ºC],[PS04] Water temperature (Tw) [ºC],[SLC01] Water temperature (Tw) [ºC],[SLC02] Water temperature (Tw) [ºC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]
0,2014-01-31,301.200000,240.600000,239.800000,240.900000,234.500000,239.100000,0.210000,0.016000,0.016000,...,27.200000,27.400000,25.500000,26.900000,5.700000,11.000000,8.300000,8.800000,12.000000,9.000000
1,2014-02-28,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,...,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571
2,2014-03-31,204.600000,142.800000,182.900000,154.500000,146.400000,191.000000,0.006500,0.001200,269.528571,...,21.900000,22.100000,18.700000,18.800000,13.000000,15.000000,19.000000,15.000000,18.000000,15.000000
3,2014-04-30,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,...,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571
4,2014-05-31,187.300000,132.300000,104.600000,95.500000,143.700000,173.600000,0.016000,0.016000,0.016000,...,18.000000,18.000000,17.200000,17.000000,15.000000,25.000000,25.000000,26.000000,18.000000,18.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2020-04-30,416.100000,269.528571,269.528571,269.528571,223.500000,423.400000,0.077000,269.528571,269.528571,...,269.528571,269.528571,18.900000,19.300000,16.100000,269.528571,269.528571,269.528571,64.700000,8.960000
76,2020-05-31,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,...,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571
77,2020-06-30,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,...,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571
78,2020-07-31,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,...,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571
79,2020-08-31,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,...,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571,269.528571

In [ ]:
df=df.dropna()
df

,date,[PS01=SLC03] Electrical conductivity (EC) [µS/cm],[PS02] Electrical conductivity (EC) [µS/cm],[PS03] Electrical conductivity (EC) [µS/cm],[PS04] Electrical conductivity (EC) [µS/cm],[SLC01] Electrical conductivity (EC) [µS/cm],[SLC02] Electrical conductivity (EC) [µS/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],...,[PS03] Water temperature (Tw) [ºC],[PS04] Water temperature (Tw) [ºC],[SLC01] Water temperature (Tw) [ºC],[SLC02] Water temperature (Tw) [ºC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]
0,2014-01-31,301.2,240.6,239.8,240.9,234.5,239.1,0.2100,0.0160,0.0160,...,27.2,27.4,25.5,26.9,5.70,11.00,8.3,8.80,12.0,9.00
6,2014-07-31,81.0,72.3,62.0,65.6,78.9,78.3,0.0200,0.0200,0.0200,...,12.5,12.5,9.4,10.6,45.00,40.00,50.0,40.00,40.0,45.00
8,2014-09-30,155.5,66.8,57.8,61.2,139.1,143.1,0.0920,0.0160,0.0160,...,16.9,18.6,17.2,16.6,21.00,27.00,29.0,27.00,20.0,22.00
22,2015-11-30,344.8,184.7,192.6,188.3,315.0,336.2,0.0230,0.0230,0.0230,...,21.4,21.7,21.6,21.8,5.50,22.00,23.0,22.00,9.2,9.50
24,2016-01-31,266.9,165.4,166.6,176.2,168.2,243.2,0.0190,0.0190,0.0190,...,26.3,26.3,24.2,26.2,9.40,13.00,14.0,17.00,12.0,12.00
33,2016-10-31,328.6,149.2,205.4,153.4,272.6,303.5,0.0190,0.0190,0.0190,...,19.1,20.6,18.9,18.0,3.30,20.00,17.0,19.00,9.2,4.70
37,2017-02-28,245.7,256.4,195.1,221.7,311.1,215.4,0.0000,0.0000,0.0000,...,27.4,27.8,24.0,25.7,13.00,4.40,12.0,9.10,16.0,13.00
39,2017-04-30,331.3,177.7,208.6,178.2,329.9,261.7,0.0490,0.0000,0.0000,...,19.1,19.6,18.4,18.5,2.90,16.00,21.0,16.00,2.7,3.40
45,2017-10-31,288.9,115.6,187.1,157.7,261.8,274.6,0.0540,0.0000,0.0000,...,18.9,18.8,18.6,18.2,8.80,26.00,22.0,24.00,15.0,12.00
47,2017-12-31,410.5,227.1,238.8,229.9,332.5,380.6,0.1500,0.0009,0.0009,...,25.2,25.1,23.9,25.2,1.50,11.00,13.0,13.00,5.0,2.00
49,2018-02-28,238.9,271.4,276.9,275.9,315.6,443.6,0.0550,0.0000,0.0200,...,25.5,25.5,23.8,25.9,73.50,4.81,10.2,5.86,10.2,12.80
53,2018-06-30,277.7,191.7,225.9,198.4,184.2,256.3,0.0005,0.0060,0.0150,...,12.4,12.7,10.9,11.0,16.50,16.10,17.8,17.30,29.1,15.80
55,2018-08-31,226.7,98.4,124.7,106.9,166.4,207.6,0.0140,0.0160,0.0150,...,13.1,13.3,13.1,12.7,21.50,40.60,37.7,41.40,22.7,21.30
57,2018-10-31,258.0,150.9,143.2,139.8,198.9,233.6,0.0120,0.0130,0.0230,...,22.6,20.9,20.7,19.3,20.40,24.90,23.7,28.40,20.1,16.40
59,2018-12-31,309.7,203.5,223.4,213.8,258.4,275.3,0.0170,0.0005,0.0120,...,22.5,22.8,22.7,22.5,8.31,17.30,18.0,17.60,15.0,15.00
73,2020-02-29,382.8,216.6,225.6,219.4,356.2,406.1,0.0170,0.0000,0.0000,...,26.2,26.3,24.6,26.7,10.40,17.10,18.3,23.20,18.1,6.14

In [ ]:
a = df.copy()

In [ ]:
a

,date,[PS01=SLC03] Electrical conductivity (EC) [µS/cm],[PS02] Electrical conductivity (EC) [µS/cm],[PS03] Electrical conductivity (EC) [µS/cm],[PS04] Electrical conductivity (EC) [µS/cm],[SLC01] Electrical conductivity (EC) [µS/cm],[SLC02] Electrical conductivity (EC) [µS/cm],[PS01=SLC03] Nitrite (NO2-N) [mg NO2-N/L],[PS02] Nitrite (NO2-N) [mg NO2-N/L],[PS03] Nitrite (NO2-N) [mg NO2-N/L],...,[PS03] Water temperature (Tw) [ºC],[PS04] Water temperature (Tw) [ºC],[SLC01] Water temperature (Tw) [ºC],[SLC02] Water temperature (Tw) [ºC],[PS01=SLC03] Turbidity (Turb) [NTU],[PS02] Turbidity (Turb) [NTU],[PS03] Turbidity (Turb) [NTU],[PS04] Turbidity (Turb) [NTU],[SLC01] Turbidity (Turb) [NTU],[SLC02] Turbidity (Turb) [NTU]
0,2014-01-31,301.2,240.6,239.8,240.9,234.5,239.1,0.2100,0.0160,0.0160,...,27.2,27.4,25.5,26.9,5.70,11.00,8.3,8.80,12.0,9.00
6,2014-07-31,81.0,72.3,62.0,65.6,78.9,78.3,0.0200,0.0200,0.0200,...,12.5,12.5,9.4,10.6,45.00,40.00,50.0,40.00,40.0,45.00
8,2014-09-30,155.5,66.8,57.8,61.2,139.1,143.1,0.0920,0.0160,0.0160,...,16.9,18.6,17.2,16.6,21.00,27.00,29.0,27.00,20.0,22.00
22,2015-11-30,344.8,184.7,192.6,188.3,315.0,336.2,0.0230,0.0230,0.0230,...,21.4,21.7,21.6,21.8,5.50,22.00,23.0,22.00,9.2,9.50
24,2016-01-31,266.9,165.4,166.6,176.2,168.2,243.2,0.0190,0.0190,0.0190,...,26.3,26.3,24.2,26.2,9.40,13.00,14.0,17.00,12.0,12.00
33,2016-10-31,328.6,149.2,205.4,153.4,272.6,303.5,0.0190,0.0190,0.0190,...,19.1,20.6,18.9,18.0,3.30,20.00,17.0,19.00,9.2,4.70
37,2017-02-28,245.7,256.4,195.1,221.7,311.1,215.4,0.0000,0.0000,0.0000,...,27.4,27.8,24.0,25.7,13.00,4.40,12.0,9.10,16.0,13.00
39,2017-04-30,331.3,177.7,208.6,178.2,329.9,261.7,0.0490,0.0000,0.0000,...,19.1,19.6,18.4,18.5,2.90,16.00,21.0,16.00,2.7,3.40
45,2017-10-31,288.9,115.6,187.1,157.7,261.8,274.6,0.0540,0.0000,0.0000,...,18.9,18.8,18.6,18.2,8.80,26.00,22.0,24.00,15.0,12.00
47,2017-12-31,410.5,227.1,238.8,229.9,332.5,380.6,0.1500,0.0009,0.0009,...,25.2,25.1,23.9,25.2,1.50,11.00,13.0,13.00,5.0,2.00
49,2018-02-28,238.9,271.4,276.9,275.9,315.6,443.6,0.0550,0.0000,0.0200,...,25.5,25.5,23.8,25.9,73.50,4.81,10.2,5.86,10.2,12.80
53,2018-06-30,277.7,191.7,225.9,198.4,184.2,256.3,0.0005,0.0060,0.0150,...,12.4,12.7,10.9,11.0,16.50,16.10,17.8,17.30,29.1,15.80
55,2018-08-31,226.7,98.4,124.7,106.9,166.4,207.6,0.0140,0.0160,0.0150,...,13.1,13.3,13.1,12.7,21.50,40.60,37.7,41.40,22.7,21.30
57,2018-10-31,258.0,150.9,143.2,139.8,198.9,233.6,0.0120,0.0130,0.0230,...,22.6,20.9,20.7,19.3,20.40,24.90,23.7,28.40,20.1,16.40
59,2018-12-31,309.7,203.5,223.4,213.8,258.4,275.3,0.0170,0.0005,0.0120,...,22.5,22.8,22.7,22.5,8.31,17.30,18.0,17.60,15.0,15.00
73,2020-02-29,382.8,216.6,225.6,219.4,356.2,406.1,0.0170,0.0000,0.0000,...,26.2,26.3,24.6,26.7,10.40,17.10,18.3,23.20,18.1,6.14